### ISSUE TITLE
Error: The `add-path` command is disabled.

### ISSUE THREAD

**Issue by maelcaldas** [mathrix-education/setup-gcloud#20]
GitHub deprecated set-env and add-path commands.

From today on, build started getting broken with the following errors:

Error: Unable to process command '::add-path::/usr/lib/google-cloud-sdk/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

uses: mathrix-education/setup-gcloud@1.2.1

Maybe upgrade @actions/core as suggested in #19  might fix it?

**Comment by Colum** [comment]
I tried to set `ACTIONS_ALLOW_UNSECURE_COMMANDS: true` as a quick band aid measure today, I set the env in the job level, action level and step level, but id did not fix the error. My guess is the env is not propagated downstream to the step but I could be wrong. 

Also looking forward to this fix.

**Comment by mathieu-bour** [comment]
Hello, I'm working on a fix and will release it today!

**Comment by mathieu-bour** [comment]
Version 1.2.2 should fix the issue, feel free to re-open @maelcaldas @Colum if you have any issue.
